"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { motion } from "framer-motion";
import { Chart as ChartJS, ArcElement, BarElement, CategoryScale, Filler, Legend, LinearScale, LineElement, PointElement, Tooltip } from "chart.js";
import { Bar, Doughnut, Line } from "react-chartjs-2";
import jsPDF from "jspdf";
import { quoteOfTheDay } from "@/data/quotes";
import { defaultData, loadData, saveData, uid } from "@/lib/storage";
import { FocusFlowData, Goal, Habit, JournalEntry, PlannerBlock, Priority, Task, TaskStatus, ThemeMode } from "@/lib/types";

ChartJS.register(ArcElement, BarElement, CategoryScale, Filler, Legend, LinearScale, LineElement, PointElement, Tooltip);

const categories = ["Work", "Study", "Health", "Business", "Personal", "Finance"];
const priorities: Priority[] = ["High", "Medium", "Low"];
const views = ["Landing", "Dashboard", "Tasks", "Focus", "Habits", "Goals", "Journal", "Analytics", "Planner", "Achievements", "Settings"] as const;
type View = (typeof views)[number];

const nav = [
  ["Dashboard", "⌘"], ["Tasks", "✓"], ["Focus", "◉"], ["Habits", "◆"], ["Goals", "◎"], ["Journal", "✎"], ["Analytics", "▣"], ["Planner", "☰"], ["Achievements", "★"], ["Settings", "⚙"]
] as const;

function todayKey() { return new Date().toISOString().slice(0, 10); }
function pct(done: number, total: number) { return total ? Math.round((done / total) * 100) : 0; }
function download(filename: string, content: string, type = "text/plain") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url);
}

export default function FocusFlowApp() {
  const [data, setData] = useState<FocusFlowData>(defaultData);
  const [view, setView] = useState<View>("Landing");
  const [taskView, setTaskView] = useState("List");
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const [timerMode, setTimerMode] = useState("Focus");
  const [customMinutes, setCustomMinutes] = useState(45);
  const [secondsLeft, setSecondsLeft] = useState(25 * 60);
  const [running, setRunning] = useState(false);

  useEffect(() => setData(loadData()), []);
  useEffect(() => saveData(data), [data]);
  useEffect(() => { document.documentElement.dataset.theme = data.settings.theme; }, [data.settings.theme]);
  useEffect(() => {
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined);
  }, []);
  useEffect(() => {
    if (!running) return;
    const id = window.setInterval(() => setSecondsLeft((s) => {
      if (s <= 1) { completeFocus(); return 0; }
      return s - 1;
    }), 1000);
    return () => clearInterval(id);
  }, [running, timerMode]);

  const stats = useMemo(() => {
    const doneTasks = data.tasks.filter((t) => t.status === "Done").length;
    const todayHabits = data.habits.filter((h) => h.completions.includes(todayKey())).length;
    const focusMinutes = data.focusHistory.reduce((sum, s) => sum + s.minutes, 0);
    const goalProgress = data.goals.length ? Math.round(data.goals.reduce((sum, g) => sum + g.targetProgress, 0) / data.goals.length) : 0;
    const score = Math.round((pct(doneTasks, data.tasks.length) + pct(todayHabits, data.habits.length) + Math.min(100, pct(focusMinutes, data.settings.dailyFocusGoal)) + goalProgress) / 4);
    return { doneTasks, todayHabits, focusMinutes, goalProgress, score, level: Math.floor(data.xp / 500) + 1 };
  }, [data]);

  function patch(updater: (d: FocusFlowData) => FocusFlowData) { setData((d) => updater(structuredClone(d))); }
  function addTask() { patch((d) => ({ ...d, tasks: [{ id: uid("task"), title: "New focused task", description: "Describe the outcome and next action.", priority: "Medium", category: "Work", dueDate: todayKey(), status: "Todo", createdAt: todayKey() }, ...d.tasks] })); setView("Tasks"); }
  function updateTask(id: string, fields: Partial<Task>) { patch((d) => ({ ...d, tasks: d.tasks.map((t) => t.id === id ? { ...t, ...fields } : t), xp: fields.status === "Done" ? d.xp + 25 : d.xp })); }
  function deleteTask(id: string) { patch((d) => ({ ...d, tasks: d.tasks.filter((t) => t.id !== id) })); }
  function addHabit() { patch((d) => ({ ...d, habits: [{ id: uid("habit"), name: "New Habit", icon: "✨", frequency: "Daily", reminderTime: "08:00", completions: [], longestStreak: 0 }, ...d.habits] })); setView("Habits"); }
  function toggleHabit(id: string) { patch((d) => ({ ...d, habits: d.habits.map((h) => h.id === id ? { ...h, completions: h.completions.includes(todayKey()) ? h.completions.filter((x) => x !== todayKey()) : [...h.completions, todayKey()], longestStreak: Math.max(h.longestStreak, h.completions.length + 1) } : h), xp: d.xp + 15 })); }
  function addGoal() { patch((d) => ({ ...d, goals: [{ id: uid("goal"), title: "New Goal", description: "Define your measurable outcome.", deadline: todayKey(), priority: "High", category: "Personal", targetProgress: 10, milestones: [{ id: uid("mile"), title: "First milestone", done: false }] }, ...d.goals] })); setView("Goals"); }
  function addJournal() { patch((d) => ({ ...d, journals: [{ id: uid("journal"), date: todayKey(), template: "Daily Reflection", wins: "", challenges: "", lessons: "", mood: "Calm", tomorrow: "", body: "" }, ...d.journals] })); setView("Journal"); }
  function addPlanner() { patch((d) => ({ ...d, planner: [...d.planner, { id: uid("plan"), time: "12:00", title: "New block", category: "Work" }].sort((a,b) => a.time.localeCompare(b.time)) })); }
  function durationFor(mode = timerMode) { return mode === "Focus" ? 25 : mode === "Short Break" ? 5 : mode === "Long Break" ? 15 : customMinutes; }
  function setMode(mode: string) { setTimerMode(mode); setRunning(false); setSecondsLeft(durationFor(mode) * 60); }
  function completeFocus() { setRunning(false); if (timerMode === "Focus") patch((d) => ({ ...d, focusHistory: [{ id: uid("focus"), mode: timerMode, minutes: Math.round(durationFor() || 25), completedAt: todayKey() }, ...d.focusHistory], xp: d.xp + 30 })); }
  function exportJSON() { download("focusflow-backup.json", JSON.stringify(data, null, 2), "application/json"); }
  function exportCSV() { download("focusflow-tasks.csv", ["Title,Priority,Category,Due Date,Status", ...data.tasks.map((t) => [t.title, t.priority, t.category, t.dueDate, t.status].map((x) => `"${x}"`).join(","))].join("\n"), "text/csv"); }
  function exportPDF() { const doc = new jsPDF(); doc.text("FocusFlow Productivity Report", 14, 18); doc.text(`Productivity Score: ${stats.score}%`, 14, 30); doc.text(`Tasks completed: ${stats.doneTasks}/${data.tasks.length}`, 14, 42); doc.text(`Focus minutes: ${stats.focusMinutes}`, 14, 54); doc.save("focusflow-report.pdf"); }

  const filteredTasks = data.tasks.filter((t) => (filter === "All" || t.status === filter || t.priority === filter || t.category === filter) && `${t.title} ${t.description}`.toLowerCase().includes(query.toLowerCase()));
  const q = quoteOfTheDay();
  const timerPct = 100 - (secondsLeft / (durationFor() * 60)) * 100;

  return <main className="min-h-screen pb-24 lg:pb-0">
    <Header view={view} setView={setView} theme={data.settings.theme} setTheme={(theme) => patch((d) => ({ ...d, settings: { ...d.settings, theme } }))} />
    {view === "Landing" && <Landing setView={setView} />}
    {view !== "Landing" && <div className="mx-auto grid w-full max-w-7xl gap-6 px-4 py-5 sm:px-6 lg:grid-cols-[240px_1fr] lg:py-8">
      <Sidebar view={view} setView={setView} />
      <section className="min-w-0 space-y-6">
        {view === "Dashboard" && <Dashboard data={data} stats={stats} quote={q} actions={{ addTask, addHabit, focus: () => setView("Focus"), journal: addJournal }} />}
        {view === "Tasks" && <Tasks data={data} tasks={filteredTasks} taskView={taskView} setTaskView={setTaskView} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} addTask={addTask} updateTask={updateTask} deleteTask={deleteTask} />}
        {view === "Focus" && <FocusTimer timerMode={timerMode} setMode={setMode} secondsLeft={secondsLeft} setSecondsLeft={setSecondsLeft} running={running} setRunning={setRunning} customMinutes={customMinutes} setCustomMinutes={setCustomMinutes} timerPct={timerPct} completeFocus={completeFocus} history={data.focusHistory} />}
        {view === "Habits" && <Habits habits={data.habits} addHabit={addHabit} toggleHabit={toggleHabit} update={(id, fields) => patch((d) => ({ ...d, habits: d.habits.map((h) => h.id === id ? { ...h, ...fields } : h) }))} />}
        {view === "Goals" && <Goals goals={data.goals} addGoal={addGoal} update={(id, fields) => patch((d) => ({ ...d, goals: d.goals.map((g) => g.id === id ? { ...g, ...fields } : g) }))} />}
        {view === "Journal" && <Journal journals={data.journals} addJournal={addJournal} update={(id, fields) => patch((d) => ({ ...d, journals: d.journals.map((j) => j.id === id ? { ...j, ...fields } : j) }))} />}
        {view === "Analytics" && <Analytics data={data} stats={stats} />}
        {view === "Planner" && <Planner blocks={data.planner} add={addPlanner} update={(id, fields) => patch((d) => ({ ...d, planner: d.planner.map((p) => p.id === id ? { ...p, ...fields } : p).sort((a,b) => a.time.localeCompare(b.time)) }))} />}
        {view === "Achievements" && <Achievements data={data} stats={stats} />}
        {view === "Settings" && <Settings data={data} patch={patch} exportJSON={exportJSON} exportCSV={exportCSV} exportPDF={exportPDF} />}
      </section>
    </div>}
    {view !== "Landing" && <BottomNav view={view} setView={setView} />}
  </main>;
}

function Header({ view, setView, theme, setTheme }: { view: View; setView: (v: View) => void; theme: ThemeMode; setTheme: (t: ThemeMode) => void }) {
  return <header className="sticky top-0 z-30 border-b border-app glass"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6">
    <button onClick={() => setView("Landing")} className="flex items-center gap-3 focus-ring rounded-2xl"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-black text-white shadow-glow">F</span><span><b>FocusFlow</b><small className="block text-muted">Productivity OS</small></span></button>
    <div className="hidden items-center gap-2 md:flex"><button onClick={() => setView(view === "Landing" ? "Dashboard" : "Landing")} className="rounded-full border border-app px-4 py-2 text-sm">{view === "Landing" ? "Open App" : "Landing"}</button><ThemeToggle theme={theme} setTheme={setTheme} /></div>
    <button onClick={() => setView("Dashboard")} className="rounded-full bg-accent px-4 py-3 text-sm font-semibold text-white md:hidden">Start</button>
  </div></header>;
}
function ThemeToggle({ theme, setTheme }: { theme: ThemeMode; setTheme: (t: ThemeMode) => void }) { return <select value={theme} onChange={(e) => setTheme(e.target.value as ThemeMode)} className="focus-ring rounded-full border border-app bg-surface px-3 py-2 text-sm"><option value="light">Light</option><option value="dark">Dark</option><option value="amoled">AMOLED</option></select>; }
function Sidebar({ view, setView }: { view: View; setView: (v: View) => void }) { return <aside className="sticky top-24 hidden h-fit rounded-[2rem] p-3 lg:block card">{nav.map(([n, icon]) => <button key={n} onClick={() => setView(n)} className={`mb-1 flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm ${view === n ? "bg-black text-white" : "hover:bg-strong"}`}><span>{icon}</span>{n}</button>)}</aside>; }
function BottomNav({ view, setView }: { view: View; setView: (v: View) => void }) { return <nav className="fixed bottom-3 left-3 right-3 z-40 mx-auto flex max-w-md justify-between rounded-[1.75rem] p-2 shadow-soft glass lg:hidden">{nav.slice(0,5).map(([n, icon]) => <button key={n} onClick={() => setView(n)} className={`min-h-12 flex-1 rounded-2xl text-xs ${view === n ? "bg-black text-white" : "text-muted"}`}><span className="block text-base">{icon}</span>{n}</button>)}</nav>; }

function Landing({ setView }: { setView: (v: View) => void }) { return <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:py-16"><div className="grid items-center gap-10 lg:grid-cols-[1fr_.9fr]"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-7"><span className="rounded-full border border-app bg-surface px-4 py-2 text-sm font-medium">Offline-first • PWA • Premium UX</span><h1 className="max-w-3xl text-5xl font-black tracking-tight sm:text-6xl lg:text-7xl">Focus Better. Achieve More.</h1><p className="max-w-2xl text-lg text-muted sm:text-xl">Manage tasks, habits, goals, focus sessions, and journals in one productivity system.</p><div className="flex flex-col gap-3 sm:flex-row"><button onClick={() => setView("Dashboard")} className="min-h-14 rounded-2xl bg-black px-7 font-bold text-white">Get Started</button><button onClick={() => setView("Analytics")} className="min-h-14 rounded-2xl border border-app bg-surface px-7 font-bold">View Demo</button></div><div className="grid gap-3 sm:grid-cols-3">{["Pomodoro timer", "Habit heatmaps", "Goal analytics"].map((x) => <div className="rounded-3xl p-4 card" key={x}><b>{x}</b><p className="mt-2 text-sm text-muted">Designed for daily consistency.</p></div>)}</div></motion.div><div className="relative"><div className="rounded-[2.5rem] p-3 shadow-glow card"><DashboardPreview /></div><div className="absolute -bottom-8 right-4 w-40 rounded-[2rem] border-4 border-black bg-surface p-3 shadow-soft sm:w-52"><div className="mb-3 h-5 rounded-full bg-strong"/><div className="grid place-items-center rounded-full bg-blue-500/10 p-7 text-3xl">◉</div><p className="mt-3 text-center text-sm font-bold">25:00 Focus</p></div></div></div></section>; }
function DashboardPreview() { return <div className="rounded-[2rem] bg-surface p-5"><div className="mb-5 flex items-center justify-between"><b>Today</b><span className="rounded-full bg-blue-500 px-3 py-1 text-xs text-white">92% Score</span></div><div className="grid gap-3 sm:grid-cols-2"><Mini label="Tasks" value="8/10"/><Mini label="Habits" value="5/6"/><Mini label="Focus" value="2.5h"/><Mini label="Streak" value="14d"/></div><div className="mt-4 h-32 rounded-3xl bg-gradient-to-br from-blue-500 to-black"/></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-strong p-4"><p className="text-xs text-muted">{label}</p><b className="text-2xl">{value}</b></div>; }

function Dashboard({ data, stats, quote, actions }: any) { return <><Title title={`Welcome back, ${data.settings.profileName}`} subtitle="Your command center for focus, consistency, and momentum." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Productivity Score" value={`${stats.score}%`} /><Stat label="Focus Time" value={`${Math.round(stats.focusMinutes / 60)}h ${stats.focusMinutes % 60}m`} /><Stat label="Current Streak" value={`${Math.max(...data.habits.map((h: Habit) => h.longestStreak), 0)} days`} /><Stat label="Level" value={stats.level} /></div><div className="grid gap-4 md:grid-cols-4">{[["Add Task",actions.addTask],["Add Habit",actions.addHabit],["Start Focus Session",actions.focus],["Write Journal",actions.journal]].map(([label, fn]: any) => <button key={label} onClick={fn} className="min-h-16 rounded-3xl bg-black px-5 font-bold text-white">{label}</button>)}</div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Today's Tasks">{data.tasks.slice(0,5).map((t: Task) => <Row key={t.id} title={t.title} meta={`${t.priority} • ${t.category}`} right={t.status} />)}</Panel><Panel title="Daily Quote"><blockquote className="text-2xl font-bold leading-tight">“{quote.text}”</blockquote><p className="mt-4 text-muted">— {quote.author} • {quote.category}</p></Panel></div><div className="grid gap-5 lg:grid-cols-3"><Panel title="Today's Habits">{data.habits.map((h: Habit) => <Row key={h.id} title={`${h.icon} ${h.name}`} meta={`${h.longestStreak} day best`} right={h.completions.includes(todayKey()) ? "Done" : "Open"} />)}</Panel><Panel title="Current Goals">{data.goals.map((g: Goal) => <Progress key={g.id} label={g.title} value={g.targetProgress} />)}</Panel><Panel title="Recent Journal Entries">{data.journals.slice(0,3).map((j: JournalEntry) => <Row key={j.id} title={j.mood} meta={j.date} right={j.template} />)}</Panel></div></>; }
function Tasks({ data, tasks, taskView, setTaskView, query, setQuery, filter, setFilter, addTask, updateTask, deleteTask }: any) { return <><Title title="Task Manager" subtitle="List, Kanban, calendar, drag-style status controls, search, and filters." action={<button onClick={addTask} className="rounded-2xl bg-accent px-5 py-3 font-bold text-white">Add Task</button>} /><div className="flex flex-col gap-3 rounded-3xl p-3 card sm:flex-row"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search tasks..." className="focus-ring min-h-12 flex-1 rounded-2xl border border-app bg-surface px-4"/><select value={filter} onChange={(e) => setFilter(e.target.value)} className="min-h-12 rounded-2xl border border-app bg-surface px-4"><option>All</option>{[...priorities, ...categories, "Todo", "In Progress", "Done"].map((x) => <option key={x}>{x}</option>)}</select><div className="flex rounded-2xl bg-strong p-1">{["List","Kanban","Calendar"].map((v) => <button key={v} onClick={() => setTaskView(v)} className={`rounded-xl px-3 py-2 text-sm ${taskView===v ? "bg-black text-white" : ""}`}>{v}</button>)}</div></div>{taskView === "Kanban" ? <div className="grid gap-4 md:grid-cols-3">{["Todo","In Progress","Done"].map((s) => <Panel key={s} title={s}>{tasks.filter((t: Task) => t.status === s).map((t: Task) => <TaskCard key={t.id} t={t} updateTask={updateTask} deleteTask={deleteTask} />)}</Panel>)}</div> : taskView === "Calendar" ? <Panel title="Calendar View">{tasks.sort((a: Task,b: Task) => a.dueDate.localeCompare(b.dueDate)).map((t: Task) => <Row key={t.id} title={t.title} meta={`${t.dueDate} • ${t.category}`} right={t.status} />)}</Panel> : <div className="space-y-3">{tasks.map((t: Task) => <TaskCard key={t.id} t={t} updateTask={updateTask} deleteTask={deleteTask} />)}</div>}</>; }
function TaskCard({ t, updateTask, deleteTask }: { t: Task; updateTask: (id:string,f:Partial<Task>)=>void; deleteTask: (id:string)=>void }) { return <div className="rounded-3xl p-4 card"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><input value={t.title} onChange={(e)=>updateTask(t.id,{title:e.target.value})} className="min-w-0 flex-1 bg-transparent text-lg font-bold outline-none"/><button onClick={()=>deleteTask(t.id)} className="rounded-xl px-3 py-2 text-danger">Delete</button></div><textarea value={t.description} onChange={(e)=>updateTask(t.id,{description:e.target.value})} className="mt-2 w-full resize-none bg-transparent text-sm text-muted outline-none"/><div className="mt-3 grid gap-2 sm:grid-cols-4"><Select value={t.priority} options={priorities} onChange={(v)=>updateTask(t.id,{priority:v as Priority})}/><Select value={t.category} options={categories} onChange={(v)=>updateTask(t.id,{category:v})}/><input type="date" value={t.dueDate} onChange={(e)=>updateTask(t.id,{dueDate:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/><Select value={t.status} options={["Todo","In Progress","Done"]} onChange={(v)=>updateTask(t.id,{status:v as TaskStatus})}/></div></div>; }
function FocusTimer(props: any) { const minutes = Math.floor(props.secondsLeft/60).toString().padStart(2,"0"); const seconds = (props.secondsLeft%60).toString().padStart(2,"0"); return <><Title title="Pomodoro Focus" subtitle="Focus, short break, long break, custom sessions, and offline history." /><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Panel title="Circular Timer"><div className="flex flex-wrap gap-2">{["Focus","Short Break","Long Break","Custom"].map((m)=><button key={m} onClick={()=>props.setMode(m)} className={`rounded-full px-4 py-2 ${props.timerMode===m ? "bg-black text-white" : "bg-strong"}`}>{m}</button>)}</div>{props.timerMode==="Custom"&&<input type="number" min="1" value={props.customMinutes} onChange={(e)=>{props.setCustomMinutes(Number(e.target.value)); props.setSecondsLeft(Number(e.target.value)*60);}} className="mt-3 rounded-2xl border border-app bg-surface px-4 py-3"/>}<div className="mx-auto my-8 grid aspect-square max-w-sm place-items-center rounded-full" style={{background:`conic-gradient(#3B82F6 ${props.timerPct}%, var(--surface-strong) 0)`}}><div className="grid h-[82%] w-[82%] place-items-center rounded-full bg-surface"><div className="text-center"><p className="text-muted">{props.timerMode}</p><b className="text-6xl tabular-nums">{minutes}:{seconds}</b></div></div></div><div className="grid grid-cols-3 gap-3"><button onClick={()=>props.setRunning(!props.running)} className="min-h-14 rounded-2xl bg-accent font-bold text-white">{props.running ? "Pause" : props.secondsLeft ? "Start" : "Resume"}</button><button onClick={()=>{props.setRunning(false); props.setSecondsLeft((props.timerMode==="Focus"?25:props.timerMode==="Short Break"?5:props.timerMode==="Long Break"?15:props.customMinutes)*60)}} className="rounded-2xl bg-strong font-bold">Reset</button><button onClick={props.completeFocus} className="rounded-2xl bg-black font-bold text-white">Skip</button></div></Panel><Panel title="Session History & Stats"><Stat label="Total Sessions" value={props.history.length}/><Stat label="Total Focus Hours" value={(props.history.reduce((s: number, h: any)=>s+h.minutes,0)/60).toFixed(1)}/>{props.history.slice(0,6).map((h: any)=><Row key={h.id} title={h.mode} meta={h.completedAt} right={`${h.minutes}m`}/>)}</Panel></div></>; }
function Habits({ habits, addHabit, toggleHabit, update }: any) { return <><Title title="Habit Tracker" subtitle="Daily check-ins, streaks, monthly progress, heatmaps, and analytics." action={<button onClick={addHabit} className="rounded-2xl bg-accent px-5 py-3 font-bold text-white">Add Habit</button>} /><div className="grid gap-4 lg:grid-cols-2">{habits.map((h: Habit)=><Panel key={h.id} title={`${h.icon} ${h.name}`}><div className="grid gap-2 sm:grid-cols-3"><input value={h.name} onChange={(e)=>update(h.id,{name:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/><input value={h.icon} onChange={(e)=>update(h.id,{icon:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/><input type="time" value={h.reminderTime} onChange={(e)=>update(h.id,{reminderTime:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/></div><button onClick={()=>toggleHabit(h.id)} className={`mt-4 min-h-14 w-full rounded-2xl font-bold ${h.completions.includes(todayKey())?"bg-success text-white":"bg-strong"}`}>{h.completions.includes(todayKey()) ? "Checked in today" : "Check in"}</button><Progress label="Completion Rate" value={pct(h.completions.length, 30)} /><div className="mt-4 grid gap-1" style={{ gridTemplateColumns: "repeat(15, minmax(0, 1fr))" }}>{Array.from({length:30}).map((_,i)=><span key={i} className={`h-5 rounded ${i < h.completions.length ? "bg-success" : "bg-strong"}`}/>)}</div><p className="mt-3 text-sm text-muted">Current streak: {h.completions.includes(todayKey()) ? h.completions.length : 0} • Longest streak: {h.longestStreak}</p></Panel>)}</div></>; }
function Goals({ goals, addGoal, update }: any) { return <><Title title="Goal Planner" subtitle="Milestones, deadlines, priorities, progress, and goal analytics." action={<button onClick={addGoal} className="rounded-2xl bg-accent px-5 py-3 font-bold text-white">Add Goal</button>} /><div className="grid gap-4">{goals.map((g: Goal)=><Panel key={g.id} title={g.title}><input value={g.title} onChange={(e)=>update(g.id,{title:e.target.value})} className="w-full bg-transparent text-2xl font-bold outline-none"/><textarea value={g.description} onChange={(e)=>update(g.id,{description:e.target.value})} className="mt-2 w-full bg-transparent text-muted outline-none"/><div className="grid gap-2 sm:grid-cols-4"><input type="date" value={g.deadline} onChange={(e)=>update(g.id,{deadline:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/><Select value={g.priority} options={priorities} onChange={(v)=>update(g.id,{priority:v as Priority})}/><Select value={g.category} options={categories} onChange={(v)=>update(g.id,{category:v})}/><input type="range" min="0" max="100" value={g.targetProgress} onChange={(e)=>update(g.id,{targetProgress:Number(e.target.value)})}/></div><Progress label="Goal Progress" value={g.targetProgress}/>{g.milestones.map((m)=><label key={m.id} className="mt-2 flex items-center gap-3"><input type="checkbox" checked={m.done} onChange={()=>update(g.id,{milestones:g.milestones.map((x)=>x.id===m.id?{...x,done:!x.done}:x)})}/>{m.title}</label>)}</Panel>)}</div></>; }
function Journal({ journals, addJournal, update }: any) { return <><Title title="Daily Journal" subtitle="Reflection, gratitude, success, free writing, mood tracking, search, and calendar review." action={<button onClick={addJournal} className="rounded-2xl bg-accent px-5 py-3 font-bold text-white">New Entry</button>} />{journals.map((j: JournalEntry)=><Panel key={j.id} title={`${j.date} • ${j.template}`}><div className="grid gap-2 sm:grid-cols-3"><Select value={j.template} options={["Daily Reflection","Gratitude Journal","Success Journal","Free Writing"]} onChange={(v)=>update(j.id,{template:v})}/><input type="date" value={j.date} onChange={(e)=>update(j.id,{date:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/><Select value={j.mood} options={["Focused","Calm","Happy","Tired","Stressed"]} onChange={(v)=>update(j.id,{mood:v})}/></div>{["wins","challenges","lessons","tomorrow","body"].map((field)=><textarea key={field} value={(j as any)[field]} onChange={(e)=>update(j.id,{[field]:e.target.value})} placeholder={field === "body" ? "Rich text notes..." : field.replace(/^./, c=>c.toUpperCase())} className="mt-3 w-full rounded-2xl border border-app bg-surface px-4 py-3 outline-none prose-input" />)}</Panel>)}</>; }
function Analytics({ data, stats }: any) { const chartData = { labels:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], datasets:[{ label:"Focus Minutes", data:[25,50,30,75,45,90,stats.focusMinutes], borderColor:"#3B82F6", backgroundColor:"rgba(59,130,246,.15)", fill:true }]}; return <><Title title="Progress Analytics" subtitle="Weekly and monthly reports for tasks, habits, focus, goals, and productivity score." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Task Completion" value={`${pct(stats.doneTasks,data.tasks.length)}%`}/><Stat label="Habit Completion" value={`${pct(stats.todayHabits,data.habits.length)}%`}/><Stat label="Goal Progress" value={`${stats.goalProgress}%`}/><Stat label="Productivity Score" value={`${stats.score}%`}/></div><div className="grid gap-5 lg:grid-cols-2"><Panel title="Line / Area Chart"><Line data={chartData}/></Panel><Panel title="Bar Chart"><Bar data={{labels:data.goals.map((g: Goal)=>g.title), datasets:[{label:"Progress", data:data.goals.map((g: Goal)=>g.targetProgress), backgroundColor:"#3B82F6"}]}}/></Panel><Panel title="Pie Chart"><Doughnut data={{labels:["Done","Open"], datasets:[{data:[stats.doneTasks, Math.max(0,data.tasks.length-stats.doneTasks)], backgroundColor:["#22C55E","#27272A"]}]}}/></Panel><Panel title="Monthly Report"><p className="text-muted">You completed {stats.doneTasks} tasks, logged {stats.focusMinutes} focus minutes, and maintained {stats.todayHabits} habits today.</p></Panel></div></>; }
function Planner({ blocks, add, update }: any) { return <><Title title="Daily Planner" subtitle="Timeline planning with schedule blocks and drag-style time controls." action={<button onClick={add} className="rounded-2xl bg-accent px-5 py-3 font-bold text-white">Add Block</button>} /><Panel title="Today Timeline">{blocks.map((b: PlannerBlock)=><div key={b.id} className="grid gap-3 border-l-2 border-blue-500/30 py-3 pl-4 sm:grid-cols-[110px_1fr_160px]"><input type="time" value={b.time} onChange={(e)=>update(b.id,{time:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2"/><input value={b.title} onChange={(e)=>update(b.id,{title:e.target.value})} className="rounded-2xl border border-app bg-surface px-3 py-2 font-bold"/><Select value={b.category} options={categories} onChange={(v)=>update(b.id,{category:v})}/></div>)}</Panel></>; }
function Achievements({ data, stats }: any) { const achievements = [["First Task Completed", stats.doneTasks >= 1],["7 Day Streak", Math.max(...data.habits.map((h: Habit)=>h.longestStreak),0) >= 7],["30 Day Streak", Math.max(...data.habits.map((h: Habit)=>h.longestStreak),0) >= 30],["100 Tasks Completed", stats.doneTasks >= 100],["100 Focus Sessions", data.focusHistory.length >= 100],["Goal Master", data.goals.some((g: Goal)=>g.targetProgress >= 100)],["Habit Champion", data.habits.length >= 5]]; return <><Title title="Achievements" subtitle="XP points, levels, badges, and progress tracking." /><div className="rounded-[2rem] bg-gradient-to-br from-black to-blue-700 p-6 text-white"><p className="text-white/70">Level {stats.level}</p><h2 className="text-4xl font-black">{data.xp} XP</h2><div className="mt-4 h-3 rounded-full bg-white/20"><div className="h-3 rounded-full bg-white" style={{width:`${data.xp%500/5}%`}}/></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{achievements.map(([name, unlocked]: any)=><div key={name} className={`rounded-3xl p-5 card ${unlocked ? "ring-2 ring-yellow-400" : "opacity-70"}`}><div className="text-4xl">{unlocked ? "🏆" : "🔒"}</div><b className="mt-3 block">{name}</b><p className="text-sm text-muted">{unlocked ? "Unlocked" : "Keep going"}</p></div>)}</div></>; }
function Settings({ data, patch, exportJSON, exportCSV, exportPDF }: any) { return <><Title title="Settings" subtitle="Theme, notifications, backup, export, language, profile, and productivity preferences." /><Panel title="Profile & Preferences"><div className="grid gap-3 sm:grid-cols-2"><input value={data.settings.profileName} onChange={(e)=>patch((d: FocusFlowData)=>({...d,settings:{...d.settings,profileName:e.target.value}}))} className="rounded-2xl border border-app bg-surface px-4 py-3"/><ThemeToggle theme={data.settings.theme} setTheme={(theme)=>patch((d: FocusFlowData)=>({...d,settings:{...d.settings,theme}}))}/><input type="number" value={data.settings.dailyFocusGoal} onChange={(e)=>patch((d: FocusFlowData)=>({...d,settings:{...d.settings,dailyFocusGoal:Number(e.target.value)}}))} className="rounded-2xl border border-app bg-surface px-4 py-3"/><select value={data.settings.language} onChange={(e)=>patch((d: FocusFlowData)=>({...d,settings:{...d.settings,language:e.target.value}}))} className="rounded-2xl border border-app bg-surface px-4 py-3"><option>English</option><option>Arabic</option><option>Spanish</option></select></div><label className="mt-4 flex items-center gap-3"><input type="checkbox" checked={data.settings.notifications} onChange={(e)=>patch((d: FocusFlowData)=>({...d,settings:{...d.settings,notifications:e.target.checked}}))}/> Enable local notifications</label></Panel><Panel title="Data Backup & Export"><div className="grid gap-3 sm:grid-cols-3"><button onClick={exportJSON} className="min-h-14 rounded-2xl bg-black font-bold text-white">Export JSON</button><button onClick={exportCSV} className="min-h-14 rounded-2xl bg-strong font-bold">Export CSV</button><button onClick={exportPDF} className="min-h-14 rounded-2xl bg-accent font-bold text-white">Export PDF</button></div><button onClick={()=>{localStorage.removeItem("focusflow:v1"); location.reload();}} className="mt-4 text-danger">Reset local data</button></Panel></>; }

function Title({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-muted">{subtitle}</p></div>{action}</div>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-[2rem] p-5 card"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</section>; }
function Stat({ label, value }: { label: string; value: any }) { return <div className="rounded-3xl p-5 card"><p className="text-sm text-muted">{label}</p><b className="mt-2 block text-3xl">{value}</b></div>; }
function Row({ title, meta, right }: { title: string; meta: string; right: string }) { return <div className="mb-2 flex items-center justify-between gap-3 rounded-2xl bg-strong p-3"><div className="min-w-0"><b className="block truncate">{title}</b><p className="truncate text-sm text-muted">{meta}</p></div><span className="shrink-0 rounded-full bg-surface px-3 py-1 text-xs font-bold">{right}</span></div>; }
function Progress({ label, value }: { label: string; value: number }) { return <div className="mt-4"><div className="mb-2 flex justify-between text-sm"><b>{label}</b><span className="text-muted">{value}%</span></div><div className="h-3 rounded-full bg-strong"><div className="h-3 rounded-full bg-accent" style={{ width: `${Math.min(100, Math.max(0, value))}%` }}/></div></div>; }
function Select({ value, options, onChange }: { value: string; options: readonly string[]; onChange: (v: string)=>void }) { return <select value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-2xl border border-app bg-surface px-3 py-2">{options.map((o)=><option key={o}>{o}</option>)}</select>; }
